-- Baseline sync migration — closes schema drift between schema.prisma and migrations
-- Generated by: prisma migrate diff --from-migrations --to-schema-datamodel --script
-- Date: 2026-06-15

-- AlterEnum
DO $$ BEGIN
  ALTER TYPE "ChatSenderType" ADD VALUE 'BOT';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AlterTable
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "externalMsgId" TEXT;

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "report_dispatch_settings" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "support_tickets"
  ADD COLUMN IF NOT EXISTS "externalChatId" TEXT,
  ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'WEB';

-- AlterTable
ALTER TABLE "tenants"
  ADD COLUMN IF NOT EXISTS "affiliateSource"    TEXT,
  ADD COLUMN IF NOT EXISTS "affiliateUrl"       TEXT,
  ADD COLUMN IF NOT EXISTS "amenitiesHighlights" TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "bookingPhone"       TEXT,
  ADD COLUMN IF NOT EXISTS "coverImageUrl"      TEXT,
  ADD COLUMN IF NOT EXISTS "discoveryTier"      TEXT NOT NULL DEFAULT 'free',
  ADD COLUMN IF NOT EXISTS "featuredBadge"      TEXT,
  ADD COLUMN IF NOT EXISTS "featuredUntil"      TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "galleryImages"      TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "instagramHandle"    TEXT,
  ADD COLUMN IF NOT EXISTS "latitude"           DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "longitude"          DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "priceFrom"          DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "resortCategory"     TEXT,
  ADD COLUMN IF NOT EXISTS "shortDescription"   TEXT,
  ADD COLUMN IF NOT EXISTS "telegramBotToken"   TEXT,
  ADD COLUMN IF NOT EXISTS "telegramNotifChatId" TEXT;

-- CreateTable (IF NOT EXISTS guard for idempotency)
CREATE TABLE IF NOT EXISTS "discovery_clicks" (
    "id"        TEXT NOT NULL,
    "tenantId"  TEXT NOT NULL,
    "type"      TEXT NOT NULL,
    "source"    TEXT,
    "country"   TEXT,
    "userAgent" TEXT,
    "referrer"  TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "discovery_clicks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "discovery_clicks_tenantId_createdAt_idx" ON "discovery_clicks"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "discovery_clicks_tenantId_type_idx"      ON "discovery_clicks"("tenantId", "type");
CREATE INDEX IF NOT EXISTS "support_tickets_source_idx"              ON "support_tickets"("source");

-- AddForeignKey (only if not already present)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'discovery_clicks_tenantId_fkey'
  ) THEN
    ALTER TABLE "discovery_clicks"
      ADD CONSTRAINT "discovery_clicks_tenantId_fkey"
      FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
