name: resortpro
services:
  postgres:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-resortpro}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB:-resortpro}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks: [coolify]
    healthcheck: {test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER:-resortpro}'], interval: 10s, timeout: 5s, retries: 10, start_period: 20s}
  redis:
    image: 'redis:7-alpine'
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks: [coolify]
    healthcheck: {test: [CMD, redis-cli, ping], interval: 10s, timeout: 5s, retries: 10, start_period: 10s}
  api:
    image: 'ghcr.io/asadsnapper-beep/resort-pro-api:21b28bb4ea2778ee48768ef652b4bbbadd578781'
    pull_policy: always
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: 'postgresql://${POSTGRES_USER:-resortpro}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-resortpro}'
      REDIS_URL: 'redis://redis:6379'
      JWT_SECRET: '${JWT_SECRET}'
      JWT_EXPIRES_IN: '${JWT_EXPIRES_IN:-7d}'
      CORS_ORIGIN: '${WEB_URL}'
      APP_DOMAIN: '${APP_DOMAIN}'
      APP_IP: '${APP_IP:-}'
      RESEND_API_KEY: '${RESEND_API_KEY:-}'
      SUPER_ADMIN_EMAILS: '${SUPER_ADMIN_EMAILS:-}'
      BKASH_PRICE_STARTER: '${BKASH_PRICE_STARTER:-}'
      BKASH_PRICE_STARTER_ANNUAL: '${BKASH_PRICE_STARTER_ANNUAL:-}'
      BKASH_PRICE_PRO: '${BKASH_PRICE_PRO:-}'
      BKASH_PRICE_PRO_ANNUAL: '${BKASH_PRICE_PRO_ANNUAL:-}'
      BKASH_PRICE_ENTERPRISE: '${BKASH_PRICE_ENTERPRISE:-}'
      BKASH_PRICE_ENTERPRISE_ANNUAL: '${BKASH_PRICE_ENTERPRISE_ANNUAL:-}'
      LAUNCH_PROMOTION_ENABLED: '${LAUNCH_PROMOTION_ENABLED:-false}'
      LAUNCH_PROMOTION_START_AT: '${LAUNCH_PROMOTION_START_AT:-}'
      LAUNCH_PROMOTION_END_AT: '${LAUNCH_PROMOTION_END_AT:-}'
      NEXT_PUBLIC_APP_URL: '${WEB_URL}'
      SEED_DEMO_REFRESH: '1'
      STORAGE_LOCAL_DIR: /app/uploads
    volumes:
      - 'uploads_data:/app/uploads'
    networks: [coolify]
    depends_on: {postgres: {condition: service_healthy}, redis: {condition: service_healthy}}
    healthcheck: {test: [CMD-SHELL, 'wget -qO- http://localhost:4000/health || exit 1'], interval: 15s, timeout: 10s, start_period: 60s, retries: 5}
  web:
    image: 'ghcr.io/asadsnapper-beep/resort-pro-web:21b28bb4ea2778ee48768ef652b4bbbadd578781'
    pull_policy: always
    restart: unless-stopped
    environment: {NODE_ENV: production, NEXT_PUBLIC_API_URL: '${API_URL}'}
    networks: [coolify]
    depends_on: {api: {condition: service_healthy}}
volumes:
  postgres_data: null
  redis_data: null
  uploads_data: null
networks:
  coolify: {external: true}
